src/bid/encoding.rs
src/lib.rs
src/proof.rs
src/score_gen/score.rs

Remove `jubjub_scalar_to_bls12_381`

---

Cargo.toml
src/proof.rs
src/score_gen.rs
src/score_gen/mod.rs
src/score_gen/score.rs

Port gadgets from `plonk_gadgets` repo and remove the ones defined here.

---

Cargo.toml
src/bid/bid.rs
src/bid/encoding.rs
src/bid/errors.rs
src/lib.rs
src/proof.rs
src/score_gen/score.rs

Implements #46 - Poseidon cipher to encrypt value

---

src/bid/bid.rs

This will be used to compare the equality of Bids on scan routines and filtering

Implement hash(), PartialEq and Eq for Bid

---

Cargo.toml
src/proof.rs
tests/bid_tests.rs

Poseidon252 API was changed and also the circuits that it produces when calling `merkle_opening_gadget`.
Therefore, we need to update our usage of this dep and also, bump the version of the crate.

Update Poseidon dep

---

.github/workflows/dusk_ci.yml
Cargo.toml
src/bid/bid.rs
src/bid/encoding.rs
src/bid/mod.rs
src/score_gen/mod.rs
src/score_gen/score.rs
tests/bid_tests.rs

Export BID_SIZE ctant publicly through a const fn

---

Cargo.toml

Update pki to v0.5.3

---

src/bid/score.rs
src/proof/bid_tests.rs

Change consensus_round_seed to be BlsScalar instead of u64

---

CHANGELOG.md
src/bid/score.rs
src/proof/bid_tests.rs

Better score gen name

---

CHANGELOG.md
Cargo.toml
src/bid.rs
src/bid/encoding.rs
src/bid/score.rs
src/proof.rs
src/proof/tree_assets.rs

Update dependencies for crate

---

CHANGELOG.md
Cargo.toml

Bump to v0.6.0

---

CHANGELOG.md
Cargo.toml
src/bid.rs
src/proof/tree_assets.rs

Add mutable access methods missing

---

README.md
src/lib.rs

Add re-sized images to lib.rs and README.md

---

CHANGELOG.md
Cargo.toml
src/bid.rs
src/bid/encoding.rs
src/bid/score.rs
src/proof.rs
src/proof/bid_tests.rs
src/proof/tree_assets.rs

Change Bid API getters returning by ref and not value

---

.github/workflows/dusk_ci.yml
Cargo.toml
src/bid.rs
src/bid/encoding.rs
src/bid/score.rs
src/errors.rs
src/lib.rs
src/proof.rs
src/proof/bid_tests.rs
src/proof/tree_assets.rs

Update crate feature-set removing std from default

---

CHANGELOG.md
Cargo.toml
src/proof.rs

Change CIRCUIT_ID def to come from code-hasher

---

Cargo.toml
src/bid.rs
src/bid/encoding.rs
src/bid/score.rs
src/lib.rs

Change Bid struct to include Message

---

CHANGELOG.md
Cargo.toml
src/bid.rs
src/bid/encoding.rs
src/bid/score.rs
src/lib.rs

- Add `phoenix-core` to deps. [#145]
- Change Bid struct to include Message [#145]
- Change deps to remove the `rc` [#147]

Release 0.9

---

CHANGELOG.md
Cargo.toml

Release 0.10

---

CHANGELOG.md
Cargo.toml
src/bid.rs

Add Message getter for Bid structure
