- .travis.yml
- Cargo.toml
- src/bid/bid.rs
- src/bid/mod.rs
- src/lib.rs
- src/proof/blindbid_proof.rs
- src/proof/mod.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
- Added plonk, Poseidon and bls12_381 as dependencies
in `Cargo.toml`.
- Generate `Bid` structure which contains the needed fields
to generate scores and blindbidproofs.
Closes #1
- The Bids need to be capable of self-generating a Score
that is unique for them. This score can't be known "a-priori".
- Add score generation function for `Scalar`.
- Add score generation gadget for `Variable`. This is indeed
proving that the score is generated correctly.
- Add tests that prove that both impls provide the same score.
Both functions return the generated score as `Scalar` or
`Variable` depending on what the user wants.
Closes #6
> Implement Bid struct & blindbid score generation fns & gadgets

- .travis.yml
- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/bid/errors.rs
- src/bid/mod.rs
- src/lib.rs
- src/proof/blindbid_proof.rs
- src/proof/mod.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
Implements the needed encoding functionalities needed to be able to compress `Bid`s into `Scalar` so we can store them and hash them with Poseidon and `kelvin` trees.
Closes #5
> Bid encoding implementation

- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/score_gen/errors.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
Now we have a way to prove the correctness of a generated Score
for a `Bid`.
- Added tests for correct and incorrect cases.
- Circuit_size atm = 1200 constraints aprox.
The Rust code can probably be a bit better. But I mainly focused on circuit correctness on this iteration.
Closes #6
> Score generation refactor

- src/bid/encoding.rs
This PR goes inline with #15 & #14.
This provides a sub-type for `Bid` which is the `StorageBid` which will be effectively the one that get's encoded and stored in the `PoseidonTree`.
> StorageBid implementation & Bid encoding refactor

- Cargo.toml
- rustfmt.toml
- src/bid.rs
- src/bid/bid.rs
- src/bid/encoding.rs
- src/bid/mod.rs
- src/lib.rs
- src/proof.rs
- src/proof/blindbid_proof.rs
- src/proof/mod.rs
- src/score_gen.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
This PR adds the implementation of the BlindBidProof gadget which is the responsable of generating the BlindBidProof circuit.
Also includes test cases for correct and incorrect circuit declarations.
This implementation also includes a refactor on the `single_complex_rangeproof` gadget which now doesn't require to send the next pow of two as a parameter and also is generic enough to support every range you want to check.
Closes #3 
Closes #4 
NOTE:
- There are two `XXX` reminders since some of the range checks should be reviewed with Dmitry since they will maybe need another gadget.
Atm the `circuit_size` for this proof is: 43942 constraints. This basically is the same as the next power of two (which is 2^16 constraints).
That means it will take approximately according to PLONK benchmarks: …
> Blind bid proof gadget implementation

- Cargo.toml
- src/bid.rs
- src/bid/encoding.rs
- src/proof.rs
- src/score_gen/score.rs
As stated in #28 we were missing all of the ECC-gate-
dependant constraints inside of the blindbid gadgets.
With the new version of PLONK out, we were able to implement
& test them so that the Pedersen Commitments used inside are
correctly constructed and working.
Closes #28
> Add ECC-gate dependant constraints to the blindbid gadgets

- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/bid/errors.rs
- src/lib.rs
- src/proof.rs
- src/score_gen/errors.rs
- src/score_gen/score.rs
We now use `anyhow` + `thiserror` in order to manage
the error handling of the crate.
The `errors.rs` file has been refactored and everything works
with `thiserror`'s derive macros. We also added field descriptions
for the errors.
- Refactored the tests to use `anyhow::Result`.
- Updated dusk-plonk to v0.2.7 & poseidon252 to v0.6.1
> Replace failiure with `Anyhow` & `thiserror`

- src/proof.rs
As mentioned in #38 That's actually a problem since we
define `value` and `bid_value` as constant witnesses
(constraint to a constant).
This means that we're harcoding these values in the
`ProverKey` & `VerifierKey` and therefore,
the circuit is not reusable.
Solved it by assigning a normal witness inclusion for these
values.
Closes #38
> Remove ctant witness inclusions for Pedersen Comm

- .travis.yml
The name of the repo was wrong and therefore we were not getting uploaded the correct `index.html` version for the docs of the library.
This PR solves it.
> Refactor documentation upload script

- src/bid/encoding.rs
- src/proof.rs
- src/score_gen/score.rs
In order to save time and not need to switch between
coordinates constantly, we directly import the generators
in Extended Coordinates.
Closes #42
> Import GENERATORS in extended coordinates directly

- Cargo.toml
Me, @CPerezz prematurely merged #49 with a git dependency inside
that wasn't pointing to a tag/release. This is a bad practice and indeed
it can cause problems since now the branch refered in Cargo.toml
doesn't exist.
Therefore, now that we have the release, this PR updates the
`plonk_gadgets` dependency of ´dusk-blindbid` to the newest
tag `v0.2.0`.
> Fix plonk_gadgets dependency in Cargo.toml

- src/bid/bid.rs
- src/bid/encoding.rs
- src/bid/mod.rs
- src/proof.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
- tests/bid_tests.rs
- There's only a single type for the Bid now
and all of the functions related to it's creation
or encoding have been refactored to work according to
that.
- Refactored also the tests of the score generation
to work with AllocatedScalar and left public only
a `gen_score` method implemented for the `Bid` data
structure.
- The blindbid gadget wasn't having the appropiate fn
signatures and wasn't using the single Bid structure
approach introduced on the previous commits.
Also, the tests weren't done as integration tests.
Therefore, the signature of the gadget fn has been refactored
to accept the consensus parameters and the score in order to
make the proof.
Also, we've moved the tests from the proof.rs file to the integration
tests folder.
Closes #56
Closes #51
> Single Bid approach

- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/lib.rs
- src/proof.rs
- src/score_gen/errors.rs
- src/score_gen/score.rs
- tests/bid_tests.rs
- We were missing the `StealthAddr` type in the `Bid` struct
which is what allows us to know if we're the owner.
Added the `StealthAddr` to the `Bid` and refactored it's
associated methods.
- We were not checking correctly that the conditions
were being satisfied.
It has been actually fixed and now we correctly check the
ranges of the timestamps stored in the bid against the
latest consensus round.
Added tests for non elegible & expired Bid testcases
Closes #48
> Pki integration & Bid fields refactor

- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/bid/errors.rs
- src/proof.rs
- tests/bid_tests.rs
We were missing all of the Read/Write implementations
needed by the `Bid` structure.
This essentially implements all of the possible variants needed
by the libraries that use the blindbid as a dependency.
Closes #60
> Implement Kelvin + Read/Write =To/From bytes traits & fns

- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/proof.rs
- tests/bid_tests.rs
- Turn generate_prover_id fn public. This is needed by `rusk` since the proverId needs to be seen together with the proof of blindbid through the network.
- Moving this crate's version of `kelvin `to `0.18.0` so that now everything uses `PoseidonTree<Bid, Blake2b>. 
This was needed because we had two different versions of `kelvin` in usage at the same time and after checking it with @krl we found out that the divergency of versions was causing the problem and so, we downgraded the version of this repo.
- Updated `bid_preimage_gadget` so that now it preserver the linking of the `Variable`s used by circuits that require
this gadget.
> Make PoseidonTree<Bid, Blake2b> possible

- Cargo.toml
- src/lib.rs
- src/proof.rs
- tests/bid_tests.rs
> Circuit trait impl for BlindBid circuit

- Cargo.toml
- tests/bid_tests.rs
As stated in #67 we should have a crate name which is inline with
the rest of crates that we currently have,
Closes #67
> Normalize crate name using dusk-blindbid

- Cargo.toml
- src/proof.rs
- src/score_gen/score.rs
- tests/bid_tests.rs
We were missing this check and it's really important since
the Verifier had no way to determine wether the score that
he/she was recieving was indeed the one committed withiin
the Proof that is being verified.
- Added a PI check inside of the `gadget` fn to check that
indeed, the Score announced is the correct.
- Refactored tests to use this new PI.
- Make score_gen gadget to return a `Variable` as a result
instead of nothing.
Closes #74
> Add PI check for announced Scores

- Cargo.toml
- src/proof.rs
We currently have a problem which is that the gadget will fail if the decryption of the `PoseidonCypher` fails. This is a big issue since the verifier is not even interested in the real values. It just needs to fill the composer with dummy values.
The solution is described here:
- If the decryption fails, we just set the result to an impossible-to-obtain value.
On that way, verifiers do not get stuck on the process (they don't care) about the real values here (just about filling the
composer).  And provers won't get any info about if this secret can or not decrypt the cipher.
Bumps this crate version to `v0.2.1`
> Remap decryption errors to return dummy values

- src/proof.rs
We were having an error since we were't compiling
the circuit and just using it.
> Write PI constructor in after gadget call

- Cargo.toml
- src/proof.rs
- src/score_gen/score.rs
- tests/bid_tests.rs
We were using a variable value to do our range checks.
Therefore, this was causing problems since the circuits
were varying constantly.
It has been addressed and solved.
> Fix variable-circuit sizes issue on Score checking

- Cargo.toml
- src/proof.rs
We were experiencing proving problems in
https://github.com/dusk-network/rusk/pull/80 due to the fact that
we were doing rangeproofs with variant max ranges.
This was causing the proofs to fail when they shouldnt since the
ProverKey & VerifierKey were basically incorrect for the circuits
that the proofs were addressed for.
This has been solved and now the constraints are done against
constant max bounds by subtracting the witnesses.
> Fix Variable-length circuit issues on round checks

- Cargo.toml
- src/proof.rs
- tests/bid_tests.rs
With the new version of `dusk-plonk` the Circuit trait definition
changed and therefore we need to update the BlindBidCircuit impl
accordingly.
- Refactored the `BlindBidCircuit` fields to not be an `Option`.
- Implemented the new trait methods.
- Changed the trim size that we got with the latest version of
Poseidon.
- Refactored tests to use `BlindBidCircuit` in the correct way.
- Replaced `size` field by `trim_size`.
- Rename `pi_constructor` to `pi_positions`.
- Update `poseidon252`, `plonk_gadgets` & `dusk-plonk` to their latest
versions.
> Apply new Circuit trait API for BlindBidCircuit

- .github/workflows/dusk_ci.yml
- Cargo.toml
- src/bid/bid.rs
- src/bid/encoding.rs
- src/errors.rs
- src/lib.rs
- src/proof.rs
- src/score_gen/mod.rs
- src/score_gen/score.rs
- tests/bid_tests.rs
- tests/tree_assets.rs
This PR closes #100 by updating all deps.
- Include and substitute serde fn's by `dusk-bytes` crate ones.
- Remove legacy functions or code.
> Update lib dusk dependencies

- src/bid.rs
- src/bid/score.rs
This makes the `from_bytes` implementations look a way
cleaner since we don't need to add any kind of hardcoded
slice ranges.
Closes #105
> Use from_reader from DeserializableSlice

- CHANGELOG.md
- Cargo.toml
- src/bid.rs
As it was stated in #125 we needed to enable
this API otherways the Bid contract cannot set
the elegibility time correctly for new Bids.
Closes #125 and unblocks https://github.com/dusk-network/rusk/issues/51
> Set elegibility

- Cargo.toml
- src/bid.rs
- src/bid/encoding.rs
- src/bid/score.rs
- src/proof.rs
- src/proof/bid_tests.rs
- src/proof/tree_assets.rs
- Update `dusk-pki` from `v0.6` to `v0.7.0-rc.0`.
- Update `dusk-poseidon` from `v0.20.0` to `v0.21.0-rc.0`.
- Update `dusk-bls12_381` from `v0.6.0` to `v0.8.0-rc.0`.
- Update `dusk-jubjub` from `v0.8.0` to `v0.10.0-rc.0`.
- Update `dusk-plonk` from `v0.5` to `v0.8.0-rc.1`.
- Update `rand-core` from `v0.5` to `v0.6`.
- Update `canonical` from `v0.5` to `v0.6`.
- Update `rand` from `v0.7` to `v0.8`.
- Update `plonk_gadgets` from `v0.5` to `v0.6.0-rc.0`.
- Remove `MemStore` references from tests.
- Remove `canonical-host` from dev-deps.
- Update tests according to the new `dusk-plonk` API.
- Change `Bid::pos` method to return &u64 instead of `u64` directly.
Resolves: #127, #129
> Update dusk-plonk and canonical and related dependencies

- .github/workflows/dusk_ci.yml
- CHANGELOG.md
- Cargo.toml
- src/bid.rs
- src/bid/encoding.rs
- src/bid/score.rs
- src/errors.rs
- src/lib.rs
- src/proof.rs
- src/proof/bid_tests.rs
- src/proof/tree_assets.rs
Includes the new variants to the `BlindBidError` enum and also the
`From` trait implementations from the respective error types.
Removes the usage of `anyhow` from the crate or the tests and uses always the
crate Error definition for the function signature types.
Resolves: #131
** This should be merged before #130 **
> Refactor error module and crate error handling
